### ISSUE TITLE
It seems "number separator decimal char" doesn't seem to work

### ISSUE THREAD

**Issue by Ypot** [legalnonsense/number-separator.el#2]
I get this:
![Captura](https://user-images.githubusercontent.com/30699014/103275761-2a2e6280-49c5-11eb-97ca-6c213613dd24.JPG)

I should get:
`12 345` -> OK
`123,123` -> OK
`123,12345` -> BUG?

Config:
```
;; number-separator.el
(use-package number-separator
  :custom
  (number-separator " ")
  (number-separator-interval 3)
  (number-separator-ignore-threshold 4)
  (number-separator-decimal-char ",")
  :config
  (number-separator-mode))
(number-separator-mode)
```

Offtopic: How could we get "half space" as separator, instead of the "normal" space?

**Comment by legalnonsense** [comment]
Just pushed newer version; try and see if it works now.

**Comment by Ypot** [comment]
Working, thanks :-)

Just for the record: as half space I am using the char "thin space"
